[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/sool-me/"
to = "/organisations/sool-me/"

[[redirects]]
from = "/damien-maudet/"
to = "/organisations/damien-maudet/"

[[redirects]]
from = "/plutotcool/"
to = "/organisations/plutotcool/"

[[redirects]]
from = "/sophie-taille-polian/"
to = "/organisations/sophie-taille-polian/"

[[redirects]]
from = "/categories/reseau/"
to = "/organisations/categories/reseau/"

[[redirects]]
from = "/carbonmaps/"
to = "/organisations/carbonmaps/"

[[redirects]]
from = "/categories/lutte-antilgv/"
to = "/organisations/categories/lutte-antilgv/"

[[redirects]]
from = "/editions-agullo/"
to = "/organisations/editions-agullo/"

[[redirects]]
from = "/noesya/"
to = "/organisations/noesya/"

[[redirects]]
from = "/equipe/ilona-huyn/"
to = "/equipe/ilona-huynh/"

[[redirects]]
from = "/megaphone-communication/"
to = "/organisations/megaphone-communication/"

[[redirects]]
from = "/la-france-insoumise/"
to = "/organisations/la-france-insoumise/"

